---
title: "Tracking with ARCOS.px vs TrackMate"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
    code_folding: hide
---

This Notebook plots the MOTA and MOTP metrics for synthetic data generated by the `simulation_tracking.py` script.

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="1000")
opts_chunk$set(echo=FALSE,
               cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Definitions

```{r}
library(data.table)
library(ggplot2)
library(ggthemes)
library(effsize)

lParRW = list(
  dirCore = "../../data/1_wave_simulation/",
  dirDataIn = 'output-data',
  dirPlotsOut = 'output-plots',
  fileIn = 'metrics_th0.75.csv.gz'
)

sTmp = file.path(lParRW$dirCore, lParRW$dirDataIn)
if (!(dir.exists(sTmp))) {
  dir.create(sTmp, showWarnings = F, recursive = T)
}

sTmp = file.path(lParRW$dirCore, lParRW$dirPlotsOut)
if (!(dir.exists(sTmp))) {
  dir.create(sTmp, showWarnings = F, recursive = T)
}

```


# Custom functions

```{r}
plot_metric_comparison <- function(dt, metric, scales, coord_fixed=FALSE, xlim=NULL, ylim=NULL) {
  
  p <- ggplot(dt[Metric == metric], 
              aes(x=arcospx, 
                  y=trackmate)) +
    geom_abline(slope=1, intercept=0, color='red', linetype='dashed') +
    geom_point(aes(color = as.factor(snr)),
               size = 3, 
               stroke=0, 
               alpha = 0.5) +
    scale_color_brewer(name = 'SNR', type='qual', palette='Dark2')
  
  
  if (is.null(scales)) {
    p <- p +
      facet_wrap(~sim_type, 
                 ncol = 1)
  } else if (scales %in% c('free', 'free_x', 'free_y')) {
    p <- p +
      facet_wrap(~sim_type, 
                 scales=scales,
                 ncol = 1)
  }
  
  if (coord_fixed)
    p <- p + coord_fixed(ratio=1, xlim=xlim, ylim=ylim)
  
  if (!is.null(xlim))
    p = p + xlim(xlim)
  
  if (!is.null(ylim))
    p = p + ylim(ylim)
  
  p <- p + 
    theme_few() +
    labs(title=metric,
         x='ARCOS.px',
         y='TrackMate') +
    theme(
      legend.position = 'right',
      panel.grid=element_blank(),
      panel.border=element_rect(size=0.5, colour="black"),
      panel.background=element_blank(),
      text=element_text(family="Helvetica"),
      axis.text.x=element_text(colour="black", size=10),
      axis.text.y=element_text(colour="black", size=10),
      axis.title.x=element_text(colour="black", size=12),
      axis.title.y=element_text(colour="black", size=12),
    )
  
  return(p)
}

my_calc_effsize <- function(m1, m2) {
  res <- effsize::cohen.d(m1, m2,
                          paired = T, 
                          hedges.correction = T,
                          conf.level = 0.95, 
                          noncentral = T, 
                          within = F, 
                          na.rm = T)
  
  return(list(effsz = res$estimate,
              ci_lower = res$conf.int[1],
              ci_upper = res$conf.int[2],
              magn = res$magnitude,
              n = length(m1)))
}
```

# Load data

```{r}
dt <- fread(file.path(lParRW$dirCore, lParRW$dirDataIn, lParRW$fileIn))
dt_wide <- dcast(dt, sim_type + snr + Metric + iteration ~ tracker_name, value.var = 'Value')
dt_wide <- dt_wide[complete.cases(dt_wide)]
dt_wide[,
        sim_type := factor(sim_type, 
                           level = c('sim_circles',
                                     'sim_directional',
                                     'sim_target_pattern',
                                     'sim_chaotic'))]
```


# Sample size

```{r}
dt_n <- dt[!is.na(Value), 
                .N, 
                by = .(sim_type, 
                       snr, 
                       Metric,
                       tracker_name)]
```

```{r, fig.width=12, fig.height=5}
ggplot(dt_n,
       aes(x = as.factor(snr),
           y = N)) +
  geom_bar(aes(fill = tracker_name),
           stat = 'identity',
           position = position_dodge(preserve = "single") ) + 
  facet_grid(sim_type ~ Metric) +
  theme_few()
```


# Metric comparison

```{r, fig.width=3, fig.height=8}
p1 <- plot_metric_comparison(dt_wide, 'MOTA (higher is better)', scales = 'free_y')

ggsave(file.path(lParRW$dirCore, lParRW$dirPlotsOut, 'comp_MOTA.pdf'),
       p1,
       width = 3,
       height = 8)

p1
```


```{r, fig.width=3, fig.height=8}
p2 <- plot_metric_comparison(dt_wide, 'MOTP (lower is better)', scales=NULL, coord_fixed=TRUE, xlim=c(0, .8), ylim=c(0, .8))

ggsave(file.path(lParRW$dirCore, lParRW$dirPlotsOut, 'comp_MOTP.pdf'),
       p2,
       width = 3,
       height = 8)

p2
```


# Effect size

```{r}
dt_res <- dt_wide[Metric %in% c('MOTA (higher is better)', 'MOTP (lower is better)') ,
                  my_calc_effsize(arcospx,
                                  trackmate),
                  by = .(sim_type,
                         snr,
                         Metric)]

dt_res[,
       sim_type := factor(sim_type, 
                          level = c('sim_circles',
                                    'sim_directional',
                                    'sim_target_pattern',
                                    'sim_chaotic'))]
```

```{r, fig.width=5, fig.height=6}
p3 <- ggplot(dt_res,
             aes(x = as.factor(snr),
                 y = effsz,
                 color = as.factor(magn))) +
  geom_hline(yintercept = 0, linetype='dashed', color='grey50', linewidth=0.5) +
  geom_point(size=3, stroke=0, alpha=0.7) +
  geom_errorbar(
    aes(ymin=ci_lower, ymax=ci_upper), 
    width=0.1, alpha=0.5, linewidth=0.5
  ) +
  coord_flip() +
  facet_grid(sim_type ~ Metric, 
             scales = 'free_x') +
  ggthemes::scale_color_colorblind("Effect size\ninterpretation:") + 
  ggthemes::theme_few() +
  labs(title="Cohen's d Effect Size by SNR and Metric",
       x='SNR', y="Cohen's d (paired)") +
  theme(
    legend.position='right',
    panel.grid=element_blank(),
    panel.border=element_rect(linewidth=0.5, colour="black"),
    panel.background=element_blank(),
    text=element_text(family="Helvetica"),
    axis.text.x=element_text(colour="black", size=10),
    axis.text.y=element_text(colour="black", size=10),
    axis.title.x=element_text(colour="black", size=12),
    axis.title.y=element_text(colour="black", size=12),
  )

ggsave(file.path(lParRW$dirCore, lParRW$dirPlotsOut, 'stats_cohensd_MOTA-MOTP.pdf'),
       p3,
       width = 5,
       height = 6)

p3
```

